### ISSUE TITLE
Queried architectures counts in the experiment setting

### ISSUE THREAD

**Issue by AlbertiPot** [chenyaofo/CTNAS#1]
Hi, thanks for your nice works, I have one question when reading your papers.

In the experiments, queried pairs are 423 for NAS-Bench-101 and 1000 for MBv3 on Imagenet. Do these numbers refer to the initial training data set size for training the NAC(in Alg 1 line 5, the size of C), or the total queried pairs counts iteratively adding sampled architectures via proposed data exploration in each iteration?

Many thanks

**Comment by chenyaofo** [comment]
It refers to the initial training data set size for training the NAC.

In the data exploration, NAC may be trained with more unlabeled data sampled from the space.

**Comment by AlbertiPot** [comment]
Thanks!
