### ISSUE TITLE
Question about the architecture-accuracy pairs data.

### ISSUE THREAD

**Issue by ShunLu91** [chenyaofo/CTNAS#5]
Hello, chenyaofo.
Great thanks for your nice work and code!
I want to know that how to get the architecture-accuracy pairs. As for NAS-Bench-101, each arch has 3 validation accuracy and test accuracy metrics(by different runs). While in the provided architecture-accuracy pairs file, each arch only has 1 validation accuracy and test accuracy metric. Did you calculate their mean value or only randomly select one to get the architecture-accuracy pairs file?

**Comment by chenyaofo** [comment]
The mean value.

**Comment by ShunLu91** [comment]
Thank you very much!
